language: rust
rust:
  - nightly
cache: cargo

env:
  - ['target=i686', 'FEATURES="vga"']
  - ['target=i686', 'FEATURES="serial"']
  - ['target=x86_64', 'FEATURES="vga"']
  - ['target=x86_64', 'FEATURES="serial"']

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - rustup run nightly cargo install rustfmt-nightly --force
  - cargo install-update -a

addons:
  apt:
    packages:
      - nasm

script:
  - cargo fmt -- --write-mode=diff
  - make
