language: rust
rust:
  - nightly
cache: cargo

addons:
  apt:
    packages:
      - qemu-system-x86

before_script:
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - rustup component add rustfmt --toolchain nightly
  - cargo install-update -a

script:
  - cargo build
  - cargo test
  - cargo +nightly fmt -- --check
