language: rust
cache: cargo
rust:
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang qemu xorriso
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
script:
  - cargo fmt -- --write-mode=diff
  - make clean; make
  - make clean; make target=x86_64
matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
