language: rust
rust:
  - nightly
cache: cargo

env:
  - ['target=i686', 'ASM=clang-3.8']
  - ['target=x86_64', 'ASM=clang-3.8']
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
    packages: ['clang-3.8']

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - cargo install-update -a

sudo: false

script:
  - cargo fmt -- --write-mode=diff
  - make
