language: rust
rust:
  - nightly
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - rustup component add rustfmt-preview --toolchain nightly
  - cargo install-update -a

script:
  - cargo +nightly fmt -- --write-mode=check
  - bootimage build --target x86_64-rxinu
