language: rust
rust:
  - nightly
cache: cargo

env:
  - ['target=i686']
  - ['target=x86_64']

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - cargo install-update -a
  - cargo install rustfmt-nightly --force
  - cargo install xargo --vers 0.3.8 --force

addons:
  apt:
    packages:
      - nasm

script:
  - cargo fmt -- --write-mode=diff
  - make
