language: rust
rust:
  - nightly
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

env:
  - ['target=i686']
  - ['target=x86_64']

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - rustup run nightly cargo install rustfmt-nightly --force
  - cargo install-update -a

addons:
  apt:
    packages:
      - nasm

script:
  - cargo fmt -- --write-mode=diff
  - make FEATURES="vga serial"
