language: rust
rust:
  - nightly
cache: cargo

env:
  - 'target=i686'
    - 'FEATURES="vga"'
    - 'FEATURES="serial"'
  - 'target=x86_64'
    - 'FEATURES="vga"'
    - 'FEATURES="serial"'

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/rustfmt || cargo install rustfmt-nightly)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - cargo install-update -a

addons:
  apt:
    packages:
      - nasm

script:
  - cargo fmt -- --write-mode=diff
  - make
