language: rust
cache: cargo
env:
  - ['target=i386', 'TARGET=i686-unknown-linux-gnu', 'ASM=clang-3.8']
  - ['target=x86_64', 'TARGET=x86_64-unknown-linux-gnu', 'ASM=clang-3.8']
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
    packages: ['clang-3.8']
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qemu xorriso
  - curl https://sh.rustup.rs -sSf | bash -s -- -y
before_script:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup install nightly
  - rustup default nightly
  - rustup target add $TARGET || true
  - which rustfmt || cargo install rustfmt
script:
  - cargo fmt -- --write-mode=diff
  - make
