language: rust
cache: cargo
rust:
  - nightly
env:
  - target=i386
  - target=x86_64
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang qemu xorriso
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
  - rustup target add i686-unknown-linux-gnu
  - rustup target add x86_64-unknown-linux-gnu
script:
  - cargo fmt -- --write-mode=diff
  - make
