language: rust
rust:
  - nightly
cache:
  directories:
    - $HOME/.cargo

env:
  - ['target=i686']
  - ['target=x86_64']

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - (test -x $HOME/.cargo/bin/rustup || rustup run nightly cargo install rustfmt-nightly)
  - cargo install-update -a
  - rustup component add rustfmt-preview

addons:
  apt:
    packages:
      - nasm

script:
  - cargo fmt -- --write-mode=diff
  - make FEATURES="vga serial" RUST_TARGET_PATH=`pwd`
