language: rust
cache: cargo
rust:
  - nightly
env:
  - ['target=i386', 'TARGET=i686-unknown-linux-gnu', 'COMPILER=clang-3.8']
  - ['target=x86_64', 'TARGET=x86_64-unknown-linux-gnu', 'COMPILER=clang-3.8']
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
    packages: ['clang-3.8']
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qemu xorriso
  - curl https://sh.rustup.rs -sSf | bash -s -- -y
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
before_script:
  - ~/.cargo/bin/rustup install nightly
  - ~/.cargo/bin/rustup default nightly
  - ~/.cargo/bin/rustup target add $TARGET || true
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
script:
  - cargo fmt -- --write-mode=diff
  - make
