[package]
name = "hole_list_allocator"
version = "0.1.0"
authors = ["Rob Gries <robert.w.gries@gmail.com>"]

[dependencies]
linked_list_allocator = "0.2.5"
spin = "0.4.5"

[dependencies.lazy_static]
version = "0.2.1"
features = ["spin_no_std"]
